### NUMPY_TASK

In [21]:
import numpy as np

# 1~10까지의 요소를 ndarray에 담는다.
ndarray1 = np.arange(start=1, stop=11)
print(ndarray1)

print("=" * 50)

# 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1이다.
ndarray1 = np.arange(start=1, stop=7)[::-1]
ndarray2 = ndarray1.reshape((3, 2))
print(ndarray2)

print("=" * 50)

# 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다
# Transpose: 전치, 행과 열을 바꿔준다.
ndarray1 = np.array([10, 8, 6, 4])
ndarray2 = ndarray1.reshape((4, 1))
print(ndarray2)

print("=" * 50)

# 1~10까지의 요소를 ndarray에 담고 각 요소에 5씩 더해준다.
ndarray1 = np.arange(start=1, stop=11)
ndarray2 = ndarray1 + 5
print(ndarray2)

print("=" * 50)

# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray 만들기
ndarray1 = np.zeros((10, ), dtype=np.int32)
print(ndarray1)
print(ndarray1.dtype)

print("=" * 50)

# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray1 = np.ones((3, 4))
print(ndarray1)

print("=" * 50)

# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray1 = np.arange(stop=5)
print(ndarray1)

print("=" * 50)

# 아래의 ndarray1이 주여졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)
print(ndarray1)

print("=" * 50)

# 2 Dimesion, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))
print(ndarray2)
print(ndarray2.ndim)


print("=" * 50)

# 2 Dimesion, axis 0은 8로 변경
ndarray3 = ndarray1.reshape((8, -1))
print(ndarray3)
print(ndarray3.ndim)

print("=" * 50)

# 3 Dimesion으로 변경
ndarray4 = ndarray1.reshape((2, 2, 4))
print(ndarray4)
print(ndarray4.ndim)

print("=" * 50)

# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray4 = ndarray3.reshape((-1, 1))
print(ndarray4)
print(ndarray4.ndim)

print("=" * 50)

# ndarray3을 1 Dimesion으로 변환
# flatten: 몇 차원이든 모두 다 1차원으로 바꿔줌
print(ndarray3.flatten())
# print(ndarray3.reshape((-1, ))) 

print("=" * 50)

# 1차원 ndarray 1~100까지 값 중 97값 추출하기
ndarray = np.arange(start=1, stop=101)
print(ndarray[96])

print("=" * 50)

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=21)

# 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 값 중 15값 추출하기
ndarray2 = ndarray1.reshape((4,5))
print(ndarray2)
print(ndarray2[2, 4])

print("=" * 50)

# 2 Dimension, axis 0은 5로 변경
ndarray3 = ndarray1.reshape((5, -1))
print(ndarray3)
# 2행의 4번째 숫자 출력
print(ndarray3[1, 3])

print("=" * 50)

# 1~100중 짝수만 출력
ndarray1 = np.arange(start=1, stop=101)
print(ndarray1[ndarray1 % 2 == 0])

print("=" * 50)

# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
ndarray2 = ndarray1[ndarray1 % 2 == 0]
ndarray3 = ndarray2.reshape((10, -1))
print(ndarray3)
print("=" * 50)
ndarray4 = ndarray3[8:].flatten()
print(ndarray4)
print("=" * 50)

# 위에서 구한 요소 중 (86, 100) 좌표 구하기

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=101)
print(ndarray1)

print("=" * 50)

# 각 요소중 1의 자리수가 2인 수들만 추출하기
ndarray2 = ndarray1[ndarray1 % 10 == 2]
print(ndarray2)

print("=" * 50)

# 1~49 요소 중 2와 5의 공배수 추출하기
ndarray3 = (ndarray1[(ndarray1 % 10 == 0) & (ndarray1 < 50)])
print(ndarray3)

print("=" * 50)

# 위에서 추출한 공배수 중 20이상인 값만 추출하기
ndarray4 = (ndarray3[ndarray3 >= 20])
print(ndarray4)


# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

ndarray2 = np.array(array1)
fruit_name = ndarray2[:1].flatten()
fruit_price = ndarray2[-1]

print(fruit_name, fruit_price, sep="\n")

fruit_name_asc = fruit_name[fruit_price.argsort()[::-1]]
print(fruit_name_asc)

# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]

ndarray2 = np.array(array2)
names = ndarray2[:1].flatten()
ages = ndarray2[1].astype(np.int16)
grades = ndarray2[-1]

print(names, ages, grades)

print(names[ages.argsort()[::-1]])
print(names[grades.argsort()])

# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]
gdp_list = []
ndarray2 = np.array(array3)

nations = ndarray2[0]
gdps = ndarray2[1]


for gdp in gdps:
    gdp_list.append(gdp.replace('%', ''))

gdps = np.array(gdp_list, dtype=np.float16)

print(nations[gdps.argsort()])

[ 1  2  3  4  5  6  7  8  9 10]
==================================================
[[6 5]
 [4 3]
 [2 1]]
==================================================
[[10]
 [ 8]
 [ 6]
 [ 4]]
==================================================
[ 6  7  8  9 10 11 12 13 14 15]
==================================================
[0 0 0 0 0 0 0 0 0 0]
int32
==================================================
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
==================================================
[0 1 2 3 4]
==================================================
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
==================================================
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
2
==================================================
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
2
==================================================
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
3
==================================================
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
2
==================================================
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
==================================================
97
==================================================
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
15
==================================================
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
8
==================================================
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
==================================================
[[  2   4   6   8  10]
 [ 12  14  16  18  20]
 [ 22  24  26  28  30]
 [ 32  34  36  38  40]
 [ 42  44  46  48  50]
 [ 52  54  56  58  60]
 [ 62  64  66  68  70]
 [ 72  74  76  78  80]
 [ 82  84  86  88  90]
 [ 92  94  96  98 100]]
==================================================
[ 82  84  86  88  90  92  94  96  98 100]
==================================================
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
==================================================
[ 2 12 22 32 42 52 62 72 82 92]
==================================================
[10 20 30 40]
==================================================
[20 30 40]
['Mango' 'Apple' 'Pear' 'Pitch' 'Melon']
['1500' '1800' '2000' '2500' '8500']
['Melon' 'Pitch' 'Pear' 'Apple' 'Mango']
['둘리' '또치' '길동' '도너' '마이콜'] [ 7  9 40  5 20] ['C' 'A' 'B' 'F' 'D']
['길동' '마이콜' '또치' '둘리' '도너']
['또치' '길동' '둘리' '마이콜' '도너']
['영국' '러시아' '남아프리카 공화국' '미국' '한국']